trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOOGLE_APPLICATION_CREDENTIALS: $(System.DefaultWorkingDirectory)/gcp-key.json
  BUCKET_NAME: 'researchsite1'  # Replace with your actual bucket name

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'gcp-key.json'  # Upload the GCP key file as a Secure File in Azure DevOps

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install google-cloud-storage
    displayName: 'Install Google Cloud SDK'

  - script: |
      echo "Uploading files to GCP bucket..."
      export GOOGLE_APPLICATION_CREDENTIALS=$(GOOGLE_APPLICATION_CREDENTIALS)
      python -c "
